spring:
  application:
    name: ai-chatbot

  main:
    web-application-type: reactive

  security:
    jwt:
      expiration: 3600000

  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/ai_chatbot
    username: root
    password: mysql

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: sql
      database-platform: org.hibernate.dialect.MySQLDialect

chat:
  api:
    url: http://localhost:1234
    completionEndpoint: /v1/chat/completions
    modelEndpoint: /v1/models

logging:
  level:
    root: INFO
    com.personal.ai.chatbot: DEBUG
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    org.springframework.http.converter.json: TRACE
    org.springframework.web.reactive.function.client: TRACE
    reactor.netty: DEBUG
  file:
    name: logs/application.log
