spring:
  application:
    name: ai-chatbot

  main:
    web-application-type: reactive

  security:
    jwt:
      expiration: 3600000

  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/ai_chatbot
    username: root
    password: mysql

  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: chat_history

  sql:
    init:
      mode: always

chat:
  api:
    url: http://localhost:1234
    completionEndpoint: /v1/chat/completions
    modelEndpoint: /v1/models

logging:
  level:
    root: INFO
    com.personal.ai.chatbot: DEBUG
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: TRACE
  file:
    name: logs/application.log
